// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Job                  *Job     `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Payload) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type Job struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Users                uint32   `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	Duration             uint32   `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Container            string   `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetUsers() uint32 {
	if m != nil {
		return m.Users
	}
	return 0
}

func (m *Job) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Job) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

type Response struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *Response) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*Payload)(nil), "agent.Payload")
	proto.RegisterType((*Job)(nil), "agent.Job")
	proto.RegisterType((*Response)(nil), "agent.Response")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x8d, 0x69, 0xd2, 0x64, 0x8a, 0x0a, 0x83, 0x48, 0x28, 0x3d, 0x94, 0x9c, 0x0a, 0x42,
	0x0f, 0xd5, 0x83, 0xd7, 0xe2, 0xad, 0x27, 0xd9, 0x37, 0xd8, 0xd8, 0x41, 0x22, 0xba, 0x13, 0x66,
	0x77, 0x05, 0xdf, 0x5e, 0x32, 0xd9, 0xd8, 0xdb, 0x7e, 0xb3, 0xcc, 0xff, 0xed, 0xbf, 0xb0, 0xb2,
	0x1f, 0xe4, 0xc2, 0x7e, 0x10, 0x0e, 0x8c, 0x85, 0x42, 0x7b, 0x84, 0xe5, 0x9b, 0xfd, 0xfd, 0x62,
	0x7b, 0xc6, 0x06, 0x96, 0x3f, 0x24, 0xbe, 0x67, 0xd7, 0x64, 0xdb, 0x6c, 0x57, 0x9b, 0x19, 0x71,
	0x03, 0xf9, 0x27, 0x77, 0xcd, 0xf5, 0x36, 0xdb, 0xad, 0x0e, 0xb0, 0x9f, 0x62, 0x4e, 0xdc, 0x99,
	0x71, 0xdc, 0xf6, 0x90, 0x9f, 0xb8, 0x43, 0x84, 0x85, 0xb3, 0xdf, 0x94, 0x76, 0xf5, 0x8c, 0xf7,
	0x50, 0x44, 0x4f, 0xe2, 0x75, 0xf5, 0xc6, 0x4c, 0x80, 0x6b, 0xa8, 0xce, 0x51, 0x6c, 0x18, 0x4d,
	0xb9, 0x5e, 0xfc, 0x33, 0x6e, 0xa0, 0x7e, 0x67, 0x17, 0x6c, 0xef, 0x48, 0x9a, 0x85, 0x46, 0x5d,
	0x06, 0xed, 0x0b, 0x54, 0x86, 0xfc, 0xc0, 0xce, 0x6b, 0x36, 0x89, 0xb0, 0xa8, 0xb0, 0x32, 0x13,
	0xe0, 0x03, 0x94, 0x1c, 0xc3, 0x10, 0x83, 0x2a, 0x6b, 0x93, 0xe8, 0xf0, 0x0c, 0xc5, 0x71, 0x7c,
	0x36, 0x3e, 0x42, 0xf9, 0x2a, 0x64, 0x03, 0xe1, 0x6d, 0x2a, 0x92, 0xfa, 0xaf, 0xef, 0x12, 0xcf,
	0x86, 0xf6, 0xaa, 0x2b, 0xf5, 0xaf, 0x9e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x11, 0xa8,
	0x5f, 0x3a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	Create(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Response, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Create(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/agent.Agent/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	Create(context.Context, *Payload) (*Response, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) Create(ctx context.Context, req *Payload) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Agent/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Create(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Agent_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
